version: "3.7"

services:
  auth-ui:
    build:
      context: ./auth-ui
    ports:
      - 3000:3000
    volumes:
      - ./auth-ui:/app
      - /app/node_modules
  messages:
    links:
      - postgresd:postgresd
    environment:
      - DATABASE_URL=postgres://messages:secret@postgresd:5432/messages?sslmode=disable
      - KETO_READ_URL=http://keto:4466
      - KETO_WRITE_URL=http://keto:4467
      - JWKS_URI=http://oathkeeper:4456/.well-known/jwks.json
    build:
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
  ws-gateway:
    links:
      - postgresd:postgresd
      - messages:messages
    environment:
      - JWKS_URI=http://oathkeeper:4456/.well-known/jwks.json
      - EVENT_RULES=./config/development.yml
    build:
      context: ./ws-gateway
    ports:
      - 5001:5001
    volumes:
      - ./ws-gateway:/app
      - /app/node_modules

  kratos-migrate:
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.6.3-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  keto-migrate:
    image: oryd/keto:v0.6.0-alpha.1
    links:
      - postgresd:postgresd
    volumes:
      - ./keto:/etc/config/keto
    environment:
      - LOG_LEVEL=debug
    command: migrate sql postgres://keto:secret@postgresd:5432/keto?sslmode=disable
    restart: on-failure

  keto:
    image: oryd/keto:v0.6.0-alpha.1
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /etc/config/keto/keto.yml
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=postgres://keto:secret@postgresd:5432/keto?sslmode=disable
    restart: on-failure
    links:
      - postgresd:postgresd
    depends_on:
      - keto-migrate
    volumes:
      - ./keto:/etc/config/keto
      - /keto_namespaces

  postgresd:
    image: postgres:13.2
    volumes:
      - ./scripts/init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=kratos,keto,messages
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=secret
