name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build UI
        run:
        - cd frontend
        - npm ci
        - npm run build
        - npm run start &
      - name: Cypress run
        uses: cypress-io/github-action@v2