name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - name: Stack status
        run: docker-compose ps
      - name: Build UI
        working-directory: frontend
        run: |
          npm ci
          npm run build
          npm run start &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: cypress
          browser: chrome
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/cypress/videos
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
